name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Audit
      run: cargo audit
    - name: Build
      run: cargo build --verbose
    - name: Format
      run: cargo fmt -- --check
    - name: Check
      run: cargo check --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
